name: Appium Android

on:
  push:
    branches: [ testingV2 ]
  pull_request:
    branches: [ testingV2 ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 34 ]
        target: [ default ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup appium
        run: |
          npm install -g appium@2.0.1
          appium -v
          appium driver install uiautomator2
          appium &>/dev/null &

      - name: Run appium android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          script: mvn clean test -Pandroid
  
